"""create animal_types table

Revision ID: 3c0e6db85dfb
Revises: 9af2c508c657
Create Date: 2026-04-25 20:32:56.329574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0e6db85dfb'
down_revision: Union[str, Sequence[str], None] = '9af2c508c657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animal_types_id'), 'animal_types', ['id'], unique=False)
    op.create_index(op.f('ix_animal_types_slug'), 'animal_types', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_animal_types_slug'), table_name='animal_types')
    op.drop_index(op.f('ix_animal_types_id'), table_name='animal_types')
    op.drop_table('animal_types')
    # ### end Alembic commands ###
