"""create business_hours table

Revision ID: 5265dbdef241
Revises: 674e74ba6c1c
Create Date: 2026-04-30 14:21:20.665114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5265dbdef241'
down_revision: Union[str, Sequence[str], None] = '674e74ba6c1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('is_24h', sa.Boolean(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'day_of_week', name='uq_business_hours_day')
    )
    op.create_index(op.f('ix_business_hours_business_id'), 'business_hours', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_hours_id'), 'business_hours', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_hours_id'), table_name='business_hours')
    op.drop_index(op.f('ix_business_hours_business_id'), table_name='business_hours')
    op.drop_table('business_hours')
    # ### end Alembic commands ###
