"""create business many-to-many junction tables

Revision ID: 674e74ba6c1c
Revises: 65ec1f98590c
Create Date: 2026-04-30 14:10:34.187177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '674e74ba6c1c'
down_revision: Union[str, Sequence[str], None] = '65ec1f98590c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_animal_types',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('animal_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_type_id'], ['animal_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('business_id', 'animal_type_id')
    )
    op.create_table('business_services',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('business_id', 'service_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_services')
    op.drop_table('business_animal_types')
    # ### end Alembic commands ###
