"""add is_admin to users

Revision ID: 8102d8c6855f
Revises: 6f1e065cf942
Create Date: 2026-04-28 18:15:46.281313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8102d8c6855f'
down_revision: Union[str, Sequence[str], None] = '6f1e065cf942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'users',
    sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()),
   )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
